version: '3.9'

services:
  api:
    build: .
    environment:
      - PORT=8080
      - PostgresUser=postgres
      - PostgresDbname=postgresdb
      - PostgresPass=postgrespass
      - JWT_SECRET="mySecret"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


